package com.army.model;
// Generated Feb 7, 2020 2:37:24 PM by Hibernate Tools 5.4.7.Final

import java.math.BigDecimal;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;


/**
 * Type generated by hbm2java
 */
@Entity
public class EmployeeType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5780318143598706441L;
	@Id
	@GeneratedValue
	private Long typeId;
	private String typeName;
	@OneToMany(mappedBy="employeeType",fetch = FetchType.LAZY , cascade = CascadeType.ALL)
	@JsonIgnore
	private Set<Employee> employees;
	
	public EmployeeType() {
	}

	public EmployeeType(Long typeId) {
		this.typeId = typeId;
	}

	public EmployeeType(Long typeId, String typeName
			, Set<Employee>  employees
			) {
		this.typeId = typeId;
		this.typeName = typeName;
		this.employees = employees;
	}

	public Long getTypeId() {
		return this.typeId;
	}

	public void setTypeId(Long typeId) {
		this.typeId = typeId;
	}

	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	public Set<Employee> getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set<Employee> employees) {
		this.employees = employees;
	}

}
