package com.army.model;
// Generated Jun 9, 2020 1:26:19 PM by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "employee", schema = "public")
public class Employee implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2475118852842255703L;
	private long employeeId;
	private EmployeeType employeeType;
	private String name;
	private BigDecimal salary;
	private Set<Message> messages = new HashSet<Message>(0);

	public Employee() {
	}

	public Employee(long employeeId, EmployeeType employeeType) {
		this.employeeId = employeeId;
		this.employeeType = employeeType;
	}

	public Employee(long employeeId, EmployeeType employeeType, String name, BigDecimal salary, Set<Message> messages) {
		this.employeeId = employeeId;
		this.employeeType = employeeType;
		this.name = name;
		this.salary = salary;
		this.messages = messages;
	}

	@Id

	@Column(name = "employee_id", unique = true, nullable = false)
	public long getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(long employeeId) {
		this.employeeId = employeeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type_id", nullable = false)
	@JsonIgnore
	public EmployeeType getEmployeeType() {
		return this.employeeType;
	}

	public void setEmployeeType(EmployeeType employeeType) {
		this.employeeType = employeeType;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "salary")
	public BigDecimal getSalary() {
		return this.salary;
	}

	public void setSalary(BigDecimal salary) {
		this.salary = salary;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employee")
	@JsonIgnore
	public Set<Message> getMessages() {
		return this.messages;
	}

	public void setMessages(Set<Message> messages) {
		this.messages = messages;
	}

}
