package com.army.model;
// Generated Jun 25, 2020 1:34:54 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name = "menu", schema = "public")
public class Menu implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6788258648939358822L;
	@Id
	@Column(name = "menu_id", unique = true, nullable = false)
	private Long menuId;
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "parent_menu_id")
	private Menu parentMenu;
	@Column(name = "menu_label", length = 50)
	private String menuLabel;
	@Column(name = "url")
	private String url;
	@Column(name = "routerlink")
	private String routerlink;
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parentMenu")
	@JsonIgnore
	private Set<Menu> childMenus = new HashSet<Menu>(0);
	@Transient
	private List<Menu> childJSONMenus;
	@Column(name = "menu_seq")
	private Integer menuSeq;
	public Menu() {
	}

	public Menu(Long menuId) {
		this.menuId = menuId;
	}

	public Menu(Long menuId, Menu parentMenu, String menuLabel, String url, String routerlink, Set<Menu> childMenus,
			List<Menu> childJSONMenus, Integer menuSeq) {
		this.menuId = menuId;
		this.parentMenu = parentMenu;
		this.menuLabel = menuLabel;
		this.url = url;
		this.routerlink = routerlink;
		this.childMenus = childMenus;
		this.childJSONMenus = childJSONMenus;
		this.menuSeq = menuSeq;
	}

	public Long getMenuId() {
		return this.menuId;
	}

	public void setMenuId(Long menuId) {
		this.menuId = menuId;
	}


	public Menu getParentMenu() {
		return this.parentMenu;
	}

	public void setParentMenu(Menu parentMenu) {
		this.parentMenu = parentMenu;
	}


	public String getMenuLabel() {
		return this.menuLabel;
	}

	public void setMenuLabel(String menuLabel) {
		this.menuLabel = menuLabel;
	}


	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}


	public String getRouterlink() {
		return this.routerlink;
	}

	public void setRouterlink(String routerlink) {
		this.routerlink = routerlink;
	}
	
	public Integer getMenuSeq() {
		return this.menuSeq;
	}

	public void setMenuSeq(Integer menuSeq) {
		this.menuSeq = menuSeq;
	}

	public Set<Menu> getChildMenus() {
		return this.childMenus;
	}

	public void setChildMenus(Set<Menu> childMenus) {
		this.childMenus = childMenus;
	}
	
	
	public List<Menu> getChildJSONMenus() {
		return this.childJSONMenus;
	}

	public void setChildJSONMenus(List<Menu> childJSONMenus) {
		this.childJSONMenus = childJSONMenus;
	}
	
	

}
