package com.army.model;
// Generated Jun 9, 2020 1:26:19 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name = "message", schema = "public")
public class Message implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3003927840573285704L;
	private long messageId;
	private Employee employee;
	private String messageBody;

	public Message() {
	}

	public Message(long messageId) {
		this.messageId = messageId;
	}

	public Message(long messageId, Employee employee, String messageBody) {
		this.messageId = messageId;
		this.employee = employee;
		this.messageBody = messageBody;
	}

	@Id

	@Column(name = "message_id", unique = true, nullable = false)
	public long getMessageId() {
		return this.messageId;
	}

	public void setMessageId(long messageId) {
		this.messageId = messageId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "employee_id")
	@JsonIgnore
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@Column(name = "message_body")
	public String getMessageBody() {
		return this.messageBody;
	}

	public void setMessageBody(String messageBody) {
		this.messageBody = messageBody;
	}

}
