package com.army.model;
// Generated Jun 9, 2020 1:26:19 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Status generated by hbm2java
 */
@Entity
@Table(name = "status", schema = "public")
public class Status implements java.io.Serializable {

	private String statusId;
	private String statusName;
	private Set<EmployeeType> employeeTypes = new HashSet<EmployeeType>(0);

	public Status() {
	}

	public Status(String statusId) {
		this.statusId = statusId;
	}

	public Status(String statusId, String statusName, Set<EmployeeType> employeeTypes) {
		this.statusId = statusId;
		this.statusName = statusName;
		this.employeeTypes = employeeTypes;
	}

	@Id

	@Column(name = "status_id", unique = true, nullable = false, length = 3)
	public String getStatusId() {
		return this.statusId;
	}

	public void setStatusId(String statusId) {
		this.statusId = statusId;
	}

	@Column(name = "status_name", length = 50)
	public String getStatusName() {
		return this.statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
	@JsonIgnore
	public Set<EmployeeType> getEmployeeTypes() {
		return this.employeeTypes;
	}

	public void setEmployeeTypes(Set<EmployeeType> employeeTypes) {
		this.employeeTypes = employeeTypes;
	}

}
